### ISSUE TITLE
What is the training policy on LCPPN? 

### ISSUE THREAD

**Issue by guipaiva** [mirand863/hiclass#61]
Hello,

first of all, good job on the project, I really like it! 

I have seen that local classifier per node has specific training policies which define the positive and negative set of training examples. But as far as i saw, it does not mention what is the policy for local classifier per parent node. 

Following [this example](https://hiclass.readthedocs.io/en/latest/algorithms/local_classifier_per_parent_node.html) from the docs, does the mammal classifier takes in account all data for training or just the data from mammal and it's successors classes? 

Thanks

**Comment by mirand863** [comment]
Hello @guipaiva,

Thank you for the interest in HiClass!

The local classifier per parent node did not need a policy implemented, since it is a multi-class classifier. However, if I were to speak in terms of policies, I guess I could say the closest policy would be the siblings policy, but with a slight modification. I only get the data regarding children nodes when training a parent node, hence, the policy would be Tr+(cj) = the set of descendant categories of cj.

I hope that answers your question. :)

**Comment by guipaiva** [comment]
It does answer my question. Thanks a lot! 

Best,
